---
- name: Helps to download files
  hosts: localhost
  become: yes
  become_method: sudo 
  vars_prompt:
    - name: URL
      prompt: "Give me the url: "
      private: no    # shows what user typping
  tasks: 
   - name: Download 1 package
     get_url:
       url: "{{URL}}"   # this is variable
       dest: /tmp/