---
- name: Installs wordpress
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  ignore_errors: true
  connection: ssh
  tasks:
    - name: Install necessary package
      package:
        name: "{{item}}"
        state: latest
      with_items: 
        - wget 
        - unzip 
        - php-gb
        - httpd 
        - mysql
        - mariadb-server
        - php 
        - php-mysql 
        - php-fpm 
      ignore_errors: true

    - name: Download 1 package
      get_url: 
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/

    - name: Unzip wordpress file
      unarchive: 
        src: "/tmp/latest.tar.gz"
        dest: /var/www/html/
      become: yes
      become_method: sudo 


    - name: Move files to html folder
      hell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: true

    - name: Restart httpd
      systemd:
        name: httpd
        enabled: yes
      become: yes
      become_method: sudo